"""
SlopeSniper Trading Tools.

Safe two-step token swaps with policy enforcement.
"""

from .config import (
    PolicyConfig,
    clear_jupiter_api_key,
    clear_rpc_config,
    get_bags_api_key,
    get_bags_partner_key,
    get_deploy_config_status,
    get_jupiter_api_key,
    get_keypair,
    get_policy_config,
    get_pumpportal_api_key,
    get_pumpportal_linked_wallet,
    get_rpc_config_status,
    get_rpc_url,
    get_secret,
    get_wallet_address,
    get_wallet_fingerprint,
    get_wallet_integrity_status,
    get_wallet_sync_status,
    restore_backup_wallet,
    set_bags_api_key,
    set_pumpportal_api_key,
    set_rpc_config,
)
from .deploy import (
    deploy_token,
    deploy_token_sync,
    get_deploy_status,
    setup_pumpportal,
    setup_pumpportal_sync,
    DeployConfig,
)
from .intents import (
    INTENT_TTL_SECONDS,
    Intent,
    create_intent,
    get_intent,
    get_intent_time_remaining,
    list_pending_intents,
    mark_executed,
)
from .onboarding import (
    export_backup,
    export_wallet,
    get_status,
    list_backup_wallets,
    setup_wallet,
)
from .policy import (
    KNOWN_SAFE_MINTS,
    PolicyResult,
    check_policy,
    format_policy_result,
    is_known_safe_mint,
)
from .scanner import (
    get_watchlist,
    remove_from_watchlist,
    scan_opportunities,
    watch_token,
)
from .solana_tools import (
    SYMBOL_TO_MINT,
    quick_trade,
    resolve_token,
    solana_check_token,
    solana_get_price,
    solana_get_wallet,
    solana_quote,
    solana_resolve_token,
    solana_search_token,
    solana_swap_confirm,
)
from .strategies import (
    STRATEGY_PRESETS,
    TradingStrategy,
    calculate_pnl_for_token,
    get_active_strategy,
    get_portfolio_pnl,
    get_strategy,
    get_trade_history,
    list_strategies,
    # PnL tracking
    pnl_export,
    pnl_init,
    pnl_positions,
    pnl_reset,
    pnl_stats,
    pnl_with_baseline,
    record_trade,
    set_strategy,
)
from .targets import (
    SellTarget,
    TargetStatus,
    TargetType,
    add_target,
    check_target,
    execute_target_sell,
    format_target_for_display,
    get_active_targets,
    get_all_targets,
    get_target,
    parse_sell_amount,
    poll_targets_batch,
    remove_target,
    update_trailing_peak,
)

__all__ = [
    # Core Tools
    "solana_get_price",
    "solana_search_token",
    "solana_check_token",
    "solana_resolve_token",
    "solana_get_wallet",
    "solana_quote",
    "solana_swap_confirm",
    "quick_trade",
    "resolve_token",
    "SYMBOL_TO_MINT",
    # Onboarding
    "get_status",
    "setup_wallet",
    "export_wallet",
    "list_backup_wallets",
    "export_backup",
    # Strategies
    "set_strategy",
    "get_strategy",
    "list_strategies",
    "get_active_strategy",
    "TradingStrategy",
    "STRATEGY_PRESETS",
    # PnL tracking
    "record_trade",
    "get_trade_history",
    "calculate_pnl_for_token",
    "get_portfolio_pnl",
    "pnl_init",
    "pnl_stats",
    "pnl_positions",
    "pnl_export",
    "pnl_reset",
    "pnl_with_baseline",
    # Scanner
    "scan_opportunities",
    "watch_token",
    "get_watchlist",
    "remove_from_watchlist",
    # Config
    "get_secret",
    "get_keypair",
    "get_wallet_address",
    "get_wallet_sync_status",
    "get_wallet_integrity_status",
    "get_wallet_fingerprint",
    "restore_backup_wallet",
    "get_rpc_url",
    "get_jupiter_api_key",
    "get_policy_config",
    "PolicyConfig",
    "set_rpc_config",
    "clear_rpc_config",
    "clear_jupiter_api_key",
    "get_rpc_config_status",
    # Deployment API keys
    "get_bags_api_key",
    "get_bags_partner_key",
    "set_bags_api_key",
    "get_pumpportal_api_key",
    "get_pumpportal_linked_wallet",
    "set_pumpportal_api_key",
    "get_deploy_config_status",
    # Token Deployment
    "deploy_token",
    "deploy_token_sync",
    "get_deploy_status",
    "setup_pumpportal",
    "setup_pumpportal_sync",
    "DeployConfig",
    # Policy
    "check_policy",
    "is_known_safe_mint",
    "PolicyResult",
    "format_policy_result",
    "KNOWN_SAFE_MINTS",
    # Intents
    "create_intent",
    "get_intent",
    "mark_executed",
    "list_pending_intents",
    "get_intent_time_remaining",
    "Intent",
    "INTENT_TTL_SECONDS",
    # Targets (Auto-sell)
    "add_target",
    "get_target",
    "get_active_targets",
    "get_all_targets",
    "remove_target",
    "check_target",
    "execute_target_sell",
    "poll_targets_batch",
    "update_trailing_peak",
    "parse_sell_amount",
    "format_target_for_display",
    "SellTarget",
    "TargetType",
    "TargetStatus",
]
